FROM quay.io/quarkus/quarkus-distroless-image:1.0

LABEL org.opencontainers.image.source="https://github.com/ctron/omp-opcua-milo-test-server"

COPY target/*-runner /application

EXPOSE 8443
EXPOSE 12686

USER nonroot

CMD ["./application"]
